use std::collections::BTreeSet;
use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::io::{Cursor, Write as _};
use std::path::PathBuf;
use std::process::{Command, Stdio};

use rmpv::Value;

const DEFAULT_OUTPUT: &str = "crates/nuvim-protocol/src/generated.rs";

fn main() -> Result<(), Box<dyn Error>> {
    let mut check = false;
    let mut output = None;
    for argument in env::args().skip(1) {
        if argument == "--check" {
            check = true;
        } else if output.replace(PathBuf::from(argument)).is_some() {
            return Err("usage: nuvim-codegen [--check] [output]".into());
        }
    }
    let output = output.unwrap_or_else(|| PathBuf::from(DEFAULT_OUTPUT));
    let api_info = Command::new("nvim").arg("--api-info").output()?;
    if !api_info.status.success() {
        return Err(format!(
            "nvim --api-info failed: {}",
            String::from_utf8_lossy(&api_info.stderr).trim()
        )
        .into());
    }
    let value = rmpv::decode::read_value(&mut Cursor::new(api_info.stdout))?;
    let generated = format_source(&render(&value)?)?;
    if check {
        let current = fs::read_to_string(&output)?;
        if current != generated {
            return Err(format!(
                "{} is stale; run cargo run -p nuvim-codegen",
                output.display()
            )
            .into());
        }
    } else {
        fs::write(output, generated)?;
    }
    Ok(())
}

fn format_source(source: &str) -> Result<String, Box<dyn Error>> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()?;
    child
        .stdin
        .take()
        .ok_or("rustfmt stdin is unavailable")?
        .write_all(source.as_bytes())?;
    let output = child.wait_with_output()?;
    if !output.status.success() {
        return Err(format!(
            "rustfmt failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )
        .into());
    }
    Ok(String::from_utf8(output.stdout)?)
}

fn render(api_info: &Value) -> Result<String, Box<dyn Error>> {
    let specification = parse_api(api_info)?;
    let mut generated = String::new();
    write_preamble(&mut generated, &specification)?;
    write_metadata(&mut generated, &specification.functions)?;
    write_client(&mut generated, &specification.functions)?;
    Ok(generated)
}

struct ApiSpecification {
    major: u64,
    minor: u64,
    patch: u64,
    api_level: u64,
    api_compatible: u64,
    functions: Vec<Function>,
}

fn parse_api(api_info: &Value) -> Result<ApiSpecification, Box<dyn Error>> {
    let root = api_info.as_map().or_else(|| {
        api_info
            .as_array()
            .and_then(|items| items.get(1))
            .and_then(Value::as_map)
    });
    let root = root.ok_or("Neovim API metadata has an unexpected root")?;
    let version = field(root, "version")
        .and_then(Value::as_map)
        .ok_or("Neovim API metadata has no version")?;
    let functions = field(root, "functions")
        .and_then(Value::as_array)
        .ok_or("Neovim API metadata has no functions")?;
    let api_level = integer_field(version, "api_level")?;
    let api_compatible = integer_field(version, "api_compatible")?;
    let major = integer_field(version, "major")?;
    let minor = integer_field(version, "minor")?;
    let patch = integer_field(version, "patch")?;

    let mut parsed = functions
        .iter()
        .map(parse_function)
        .collect::<Result<Vec<_>, _>>()?;
    parsed.sort_by(|left, right| left.name.cmp(&right.name));
    Ok(ApiSpecification {
        major,
        minor,
        patch,
        api_level,
        api_compatible,
        functions: parsed,
    })
}

fn write_preamble(
    generated: &mut String,
    specification: &ApiSpecification,
) -> Result<(), std::fmt::Error> {
    generated.push_str("// @generated by `cargo run -p nuvim-codegen`; do not edit.\n\n");
    generated.push_str("use rmpv::Value;\n\n");
    generated.push_str("use crate::{RpcClient, RpcError};\n\n");
    writeln!(
        generated,
        "pub const NVIM_API_VERSION: (u64, u64, u64) = ({}, {}, {});",
        specification.major, specification.minor, specification.patch
    )?;
    writeln!(
        generated,
        "pub const NVIM_API_LEVEL: u64 = {};",
        specification.api_level
    )?;
    writeln!(
        generated,
        "pub const NVIM_API_COMPATIBLE: u64 = {};\n",
        specification.api_compatible
    )?;
    generated.push_str(
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
         pub struct ApiParameter {\n\
         \x20   pub type_name: &'static str,\n\
         \x20   pub name: &'static str,\n\
         }\n\n\
         #[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
         pub struct ApiFunction {\n\
         \x20   pub name: &'static str,\n\
         \x20   pub parameters: &'static [ApiParameter],\n\
         \x20   pub return_type: &'static str,\n\
         \x20   pub method: bool,\n\
         \x20   pub since: u64,\n\
         \x20   pub deprecated_since: Option<u64>,\n\
         }\n\n",
    );
    Ok(())
}

fn write_metadata(generated: &mut String, functions: &[Function]) -> Result<(), std::fmt::Error> {
    generated.push_str("pub static API_FUNCTIONS: &[ApiFunction] = &[\n");
    for function in functions {
        generated.push_str("    ApiFunction {\n");
        writeln!(generated, "        name: {:?},", function.name)?;
        generated.push_str("        parameters: &[\n");
        for parameter in &function.parameters {
            writeln!(
                generated,
                "            ApiParameter {{ type_name: {:?}, name: {:?} }},\n",
                parameter.type_name, parameter.name
            )?;
        }
        generated.push_str("        ],\n");
        write!(
            generated,
            "        return_type: {:?},\n        method: {},\n        since: {},\n",
            function.return_type, function.method, function.since
        )?;
        match function.deprecated_since {
            Some(level) => writeln!(generated, "        deprecated_since: Some({level}),")?,
            None => generated.push_str("        deprecated_since: None,\n"),
        }
        generated.push_str("    },\n");
    }
    generated.push_str("];\n\n");
    generated.push_str(
        "#[must_use]\n\
         pub fn api_function(name: &str) -> Option<&'static ApiFunction> {\n\
         \x20   API_FUNCTIONS\n\
         \x20       .binary_search_by_key(&name, |function| function.name)\n\
         \x20       .ok()\n\
         \x20       .map(|index| &API_FUNCTIONS[index])\n\
         }\n\n",
    );
    Ok(())
}

fn write_client(generated: &mut String, functions: &[Function]) -> Result<(), std::fmt::Error> {
    generated.push_str("impl RpcClient {\n");
    for function in functions {
        writeln!(
            generated,
            "    /// Calls `{}` from Neovim API level {}.",
            function.name, function.since
        )?;
        generated.push_str("    ///\n    /// # Errors\n");
        generated
            .push_str("    /// Returns an error when the RPC transport or Neovim call fails.\n");
        if function.parameters.is_empty() {
            writeln!(
                generated,
                "    pub fn {}(&mut self) -> Result<Value, RpcError> {{",
                function.name
            )?;
            writeln!(generated, "        self.call({:?}, vec![])", function.name)?;
        } else {
            writeln!(
                generated,
                "    pub fn {}(&mut self, arguments: [Value; {}]) -> Result<Value, RpcError> {{",
                function.name,
                function.parameters.len()
            )?;
            writeln!(
                generated,
                "        self.call({:?}, Vec::from(arguments))",
                function.name
            )?;
        }
        generated.push_str("    }\n\n");
    }
    generated.push_str("}\n");
    Ok(())
}

#[derive(Debug)]
struct Function {
    name: String,
    parameters: Vec<Parameter>,
    return_type: String,
    method: bool,
    since: u64,
    deprecated_since: Option<u64>,
}

#[derive(Debug)]
struct Parameter {
    type_name: String,
    name: String,
}

fn parse_function(value: &Value) -> Result<Function, Box<dyn Error>> {
    let map = value.as_map().ok_or("Neovim API function is not a map")?;
    let parameters = field(map, "parameters")
        .and_then(Value::as_array)
        .ok_or("Neovim API function has no parameters")?
        .iter()
        .map(|parameter| {
            let pair = parameter
                .as_array()
                .ok_or("Neovim API parameter is not a pair")?;
            Ok(Parameter {
                type_name: pair
                    .first()
                    .and_then(Value::as_str)
                    .ok_or("Neovim API parameter has no type")?
                    .to_owned(),
                name: pair
                    .get(1)
                    .and_then(Value::as_str)
                    .ok_or("Neovim API parameter has no name")?
                    .to_owned(),
            })
        })
        .collect::<Result<Vec<_>, Box<dyn Error>>>()?;
    let name = string_field(map, "name")?;
    let mut identifiers = BTreeSet::new();
    for parameter in &parameters {
        if !identifiers.insert(rust_identifier(&parameter.name)) {
            return Err(format!("{name} has duplicate Rust parameter names").into());
        }
    }
    Ok(Function {
        name,
        parameters,
        return_type: string_field(map, "return_type")?,
        method: field(map, "method")
            .and_then(Value::as_bool)
            .unwrap_or(false),
        since: integer_field(map, "since")?,
        deprecated_since: field(map, "deprecated_since").and_then(Value::as_u64),
    })
}

fn rust_identifier(name: &str) -> String {
    let mut identifier = name
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect::<String>();
    if identifier.starts_with(|character: char| character.is_ascii_digit()) {
        identifier.insert(0, '_');
    }
    if matches!(
        identifier.as_str(),
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
    ) {
        identifier.insert_str(0, "arg_");
    }
    identifier
}

fn field<'a>(map: &'a [(Value, Value)], name: &str) -> Option<&'a Value> {
    map.iter()
        .find_map(|(key, value)| (key.as_str() == Some(name)).then_some(value))
}

fn string_field(map: &[(Value, Value)], name: &str) -> Result<String, Box<dyn Error>> {
    field(map, name)
        .and_then(Value::as_str)
        .map(str::to_owned)
        .ok_or_else(|| format!("Neovim API metadata has no string {name}").into())
}

fn integer_field(map: &[(Value, Value)], name: &str) -> Result<u64, Box<dyn Error>> {
    field(map, name)
        .and_then(Value::as_u64)
        .ok_or_else(|| format!("Neovim API metadata has no integer {name}").into())
}

#[cfg(test)]
mod tests {
    use rmpv::Value;

    use super::{render, rust_identifier};

    #[test]
    fn identifiers_are_valid_and_stable() {
        assert_eq!(rust_identifier("type"), "arg_type");
        assert_eq!(rust_identifier("start-row"), "start_row");
        assert_eq!(rust_identifier("2d"), "_2d");
    }

    #[test]
    fn renders_a_client_method_and_metadata() {
        let function = Value::Map(vec![
            (Value::from("name"), Value::from("nvim_ping")),
            (
                Value::from("parameters"),
                Value::Array(vec![Value::Array(vec![
                    Value::from("String"),
                    Value::from("message"),
                ])]),
            ),
            (Value::from("return_type"), Value::from("String")),
            (Value::from("method"), Value::Boolean(false)),
            (Value::from("since"), Value::from(1)),
        ]);
        let version = Value::Map(vec![
            (Value::from("api_level"), Value::from(12)),
            (Value::from("api_compatible"), Value::from(10)),
            (Value::from("major"), Value::from(0)),
            (Value::from("minor"), Value::from(12)),
            (Value::from("patch"), Value::from(5)),
        ]);
        let api_info = Value::Array(vec![
            Value::from(1),
            Value::Map(vec![
                (Value::from("version"), version),
                (Value::from("functions"), Value::Array(vec![function])),
            ]),
        ]);
        let output = render(&api_info).expect("fixture should render");
        assert!(output.contains("pub const NVIM_API_LEVEL: u64 = 12;"));
        assert!(output.contains("pub fn nvim_ping(&mut self, arguments: [Value; 1])"));
        assert!(output.contains("self.call(\"nvim_ping\", Vec::from(arguments))"));
    }
}
